services:
  directus:
    image: directus/directus:10.13.0
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "super-secret-random-key-change-this"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      ADMIN_EMAIL: "amirfahd1521@gmail.com"
      ADMIN_PASSWORD: "james1521"
